# Generated by Django 4.2 on 2023-05-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_documentindexpage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentindexpage",
            options={"verbose_name": "Lista de Documentos"},
        ),
    ]
