# Generated by Django 5.0.10 on 2024-12-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_customdocument_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customdocument",
            name="file_size",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
