# Generated by Django 5.2 on 2025-08-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_customdocument_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
