# Generated by Django 5.1.2 on 2024-10-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aratinga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aratingatag',
            options={'verbose_name': 'Aratinga Tag'},
        ),
    ]
