# Generated by Django 5.1.2 on 2024-10-15 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aratinga', '0002_alter_aratingatag_options'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('organisation_url', models.URLField(blank=True, verbose_name='Organisation URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='layoutsettings',
            name='navbar_class',
        ),
        migrations.RemoveField(
            model_name='layoutsettings',
            name='navbar_collapse_mode',
        ),
        migrations.RemoveField(
            model_name='layoutsettings',
            name='navbar_color_scheme',
        ),
        migrations.RemoveField(
            model_name='layoutsettings',
            name='navbar_content_fluid',
        ),
        migrations.RemoveField(
            model_name='layoutsettings',
            name='navbar_fixed',
        ),
        migrations.RemoveField(
            model_name='layoutsettings',
            name='navbar_format',
        ),
        migrations.RemoveField(
            model_name='layoutsettings',
            name='navbar_search',
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_suffix', models.CharField(default='Suffix for the title', help_text="The suffix for the title meta tag e.g. ' | Federal Institute'", max_length=255, verbose_name='Title suffix')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
