# Generated by Django 5.1.2 on 2024-10-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aratinga', '0002_genericsettings_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericsettings',
            name='title_suffix',
            field=models.CharField(default='Federal Institute', help_text="The suffix for the title meta tag e.g. ' | Federal Institute'", max_length=255, verbose_name='Title suffix'),
        ),
    ]
