# Generated by Django 5.1.2 on 2024-10-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aratinga', '0003_theme_themesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.DeleteModel(
            name='ThemeSettings',
        ),
    ]
