# Generated by Django 5.1.2 on 2024-10-31 16:36

import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aratinga', '0004_carousel_classifier_carouselslide_classifierterm'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='aratingapage',
            name='classifier_terms',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Categorize and group pages together with classifiers. Used to organize and filter pages across the site.', to='aratinga.classifierterm', verbose_name='Classifiers'),
        ),
        migrations.AddField(
            model_name='aratingapage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Used to organize pages across the site.', through='aratinga.AratingaTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
