# Generated by Django 5.1.2 on 2024-11-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aratinga', '0005_aratingapage_classifier_terms_aratingapage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericsettings',
            name='title_suffix',
            field=models.CharField(default='The Jandaya Institute', help_text="The suffix for the title meta tag e.g. ' | The Jandaya Institute'", max_length=255, verbose_name='Title suffix'),
        ),
    ]
