# Generated by Django 5.1.7 on 2025-04-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aratinga', '0009_delete_theme_delete_themesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericsettings',
            name='title_suffix',
            field=models.CharField(default='Ministry of Education', help_text="The suffix for the title meta tag e.g. ' | Ministry of Education'", max_length=255, verbose_name='Title suffix'),
        ),
    ]
