# Generated by Django 5.1.1 on 2024-09-27 12:11

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aratinga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('aratingapage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aratinga.aratingapage')),
                ('body', wagtail.fields.StreamField([], blank=True, block_lookup={}, null=True)),
                ('show_images', models.BooleanField(default=True, verbose_name='Show images')),
                ('show_captions', models.BooleanField(default=True)),
                ('show_meta', models.BooleanField(default=True, verbose_name='Show author and date info')),
                ('show_preview_text', models.BooleanField(default=True, verbose_name='Show preview text')),
            ],
            options={
                'verbose_name': 'Article Landing Page',
            },
            bases=('aratinga.aratingapage',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('aratingapage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aratinga.aratingapage')),
                ('body', wagtail.fields.StreamField([], blank=True, block_lookup={}, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('author_display', models.CharField(blank=True, help_text='Override how the author’s name displays on this article.', max_length=255, verbose_name='Display author as')),
                ('date_display', models.DateField(blank=True, null=True, verbose_name='Display publish date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-first_published_at'],
            },
            bases=('aratinga.aratingapage',),
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('aratingapage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aratinga.aratingapage')),
                ('body', wagtail.fields.StreamField([], blank=True, block_lookup={}, null=True)),
            ],
            options={
                'verbose_name': 'Web Page',
            },
            bases=('aratinga.aratingapage',),
        ),
    ]
