from django.db import migrations
from wagtail.models import Locale
from aratinga.admin.thread import set_theme

def initial_data(apps, schema_editor):
    ContentType = apps.get_model('contenttypes.ContentType')
    Page = apps.get_model('wagtailcore.Page')
    Site = apps.get_model('wagtailcore.Site')
    WebPage = apps.get_model('website.WebPage')

    Theme = apps.get_model('aratingaadmin', 'Theme')
    ThemeSettings = apps.get_model('aratingaadmin', 'ThemeSettings')

    # Create page content type
    webpage_content_type, created = ContentType.objects.get_or_create(
        model='webpage',
        app_label='website',
    )

    # Delete the default home page generated by wagtail, and replace it
    # with a more useful page type. Uses _raw_delete instead of .delete()
    # on purpose: Django's normal delete collector walks every registered
    # Page subclass to cascade the deletion, including TemplatePage —
    # whose historical migration state still records it as inheriting
    # directly from Page (parent_link "page_ptr") even after aratinga's
    # 0011_templatepage_to_aratingapage_refactor re-parented it under
    # AratingaPage in the real schema. Django has no built-in migration
    # operation to update a model's recorded base classes, so that
    # mismatch is permanent for this historical state and breaks the
    # collector's join on Postgres (silently tolerated on sqlite). Safe
    # here because this is a brand-new install with a single, childless
    # default homepage — but _raw_delete also skips the FK cascade that
    # would normally remove wagtailcore's default Site row pointing at
    # this page, so that has to be deleted explicitly first or the new
    # Site created below collides on the hostname/port unique constraint.
    old_home = Page.objects.filter(slug='home').first()
    if old_home is not None:
        Site.objects.filter(root_page_id=old_home.pk).delete()
        Page.objects.filter(pk=old_home.pk)._raw_delete(
            using=schema_editor.connection.alias
        )

    homepage = WebPage.objects.create(
        title = "Home",
        slug='home',
        custom_template='aratinga/pages/web_page.html',
        content_type=webpage_content_type,
        path='00010001',
        depth=2,
        numchild=0,
        url_path='/home/',
        locale_id=Locale.get_default().id,
    )

    # Create a new default site
    site = Site.objects.create(
        hostname='localhost',
        site_name='localhost',
        root_page_id=homepage.id,
        is_default_site=True
    )

    theme = Theme.objects.create(
        name='Bootstrap5',
        description='',
        theme_path='themes/bootstrap5'
    )

    ts, created = ThemeSettings.objects.get_or_create(
        site_id=site.id,
        defaults={'theme_id': theme.id},
    )
    if not created:
        ts.theme_id = theme.id
        ts.save()


class Migration(migrations.Migration):

    dependencies = [
        # Pinado na ultima migration do aratinga que mexe no schema de
        # TemplatePage (0011): a "Page.objects...delete()" abaixo cascadeia
        # pra qualquer subclasse de Page, incluindo TemplatePage — se essa
        # migration nao tiver terminado ainda, o estado historico usado
        # aqui referencia uma coluna que a 0011 ja renomeou no banco real,
        # e a query quebra (so aparece no Postgres; sqlite reconstroi a
        # tabela inteira em cada ALTER e nao expoe essa janela).
        ('aratinga', '0011_templatepage_to_aratingapage_refactor'),
        ('wagtailcore', '0057_page_locale_fields_notnull'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_data),
    ]



