# Generated by Django 5.2 on 2025-04-03 19:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_articleindexpage_body_alter_webpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleindexpage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 2), ('promo', 4), ('featured_section', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('hero_text', 1), ('hero_cta', 1), ('hero_cta_link', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Write some promotional copy', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('promo_image', 0), ('promo_title', 1), ('promo_text', 3)]], {}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Featured section for the homepage. Will display up to three child items.', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 1), ('section', 5)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 2), ('promo', 4), ('featured_section', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('hero_text', 1), ('hero_cta', 1), ('hero_cta_link', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Write some promotional copy', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('promo_image', 0), ('promo_title', 1), ('promo_text', 3)]], {}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Featured section for the homepage. Will display up to three child items.', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 1), ('section', 5)]], {})}, null=True),
        ),
    ]
