# Generated by Django 5.2.4 on 2025-08-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_articleindexpage_body_alter_webpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleindexpage',
            name='body',
        ),
    ]
