# Generated by Django 5.2.4 on 2025-08-04 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aratinga', '0010_alter_genericsettings_title_suffix'),
        ('website', '0006_remove_articleindexpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPage',
            fields=[
                ('aratingapage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aratinga.aratingapage')),
            ],
            options={
                'verbose_name': 'Default Page',
                'ordering': ['-first_published_at'],
            },
            bases=('aratinga.aratingapage',),
        ),
        migrations.AlterModelOptions(
            name='articleindexpage',
            options={'verbose_name': 'Article List Page'},
        ),
    ]
