# Generated by Django 5.1.7 on 2025-03-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aratingaadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aratingaadmin.theme', verbose_name='Themes'),
        ),
    ]
