# Generated by Django 5.1.7 on 2025-03-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aratingaadmin', '0003_remove_theme_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
