# Generated by Django 5.1.7 on 2025-03-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aratingaadmin', '0004_alter_theme_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThemeSettings',
        ),
    ]
