# Generated by Django 5.1.2 on 2024-10-16 17:01

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('zip_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(pathlib.PurePosixPath('/home/fabio/dev.f4bio/mysite')), upload_to='themes/')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
