# Generated by Django 5.1.2 on 2024-12-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aratingathemes', '0002_themesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='theme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
