# Generated by Django 5.1.2 on 2025-03-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aratingathemes', '0004_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themesettings',
            options={'verbose_name': 'themes', 'verbose_name_plural': 'themes'},
        ),
    ]
